---
name: Perlanet
version: 0.42
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: |-
  A program for creating web pages that aggregate web feeds (both
  RSS and Atom).
license: perl
resources:
  MailingList: http://lists.mag-sol.com/mailman/listinfo/perlanet
  homepage: http://code.mag-sol.com/Perlanet/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/davorg/perlanet.git
requires:
  DateTime: 0
  DateTime::Duration: 0
  Encode: 0
  HTML::Scrubber: 0
  HTML::Tidy: 0
  List::Util: 0
  Moose: 0
  Template: 0
  TryCatch: 0
  URI::Fetch: 0
  XML::Feed: 0.22
  YAML: 0
  perl: 5.6.0
build_requires:
  File::Path: 0
  Test::More: 0
recommends:
  CHI: 0
  Compress::Zlib: 0
  XML::OPML::SimpleGen: 0
provides:
  Perlanet:
    file: lib/Perlanet.pm
    version: 0.42
  Perlanet::Entry:
    file: lib/Perlanet/Entry.pm
  Perlanet::Feed:
    file: lib/Perlanet/Feed.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - aggregate
  - aggregator
  - atom
  - feed
  - planet
  - rss
  - xml
