---
name: Perlanet
version: 0.07
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: |-
  A program for creating web pages that aggregate web feeds (both
  RSS and Atom).
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  DateTime::Duration: 0
  Encode: 0
  HTML::Scrubber: 0
  HTML::Tidy: 0
  LWP::Simple: 0
  List::Util: 0
  Template: 0
  XML::Feed: 0
  XML::OPML::SimpleGen: 0
  YAML: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Perlanet:
    file: lib/Perlanet.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
